apiVersion: v1
kind: ConfigMap
metadata:
  name: slotify-config
data:
  BETTER_AUTH_URL: "http://slotify.local"
  NEXT_PUBLIC_APP_URL: "http://slotify.local"
  RESEND_FROM_EMAIL: "Slotify <noreply@yourdomain.com>"
