apiVersion: v1
kind: Secret
metadata:
  name: slotify-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://slotifyuser:slotifypassword@postgres-service:5432/slotifydb"
  GOOGLE_CLIENT_ID: "your-google-client-id"
  GOOGLE_CLIENT_SECRET: "your-google-client-secret"
  BETTER_AUTH_SECRET: "your-32-char-secret"
  RAZORPAY_KEY_ID: "your-key-id"
  RAZORPAY_KEY_SECRET: "your-key-secret"
  RAZORPAY_WEBHOOK_SECRET: "your-webhook-secret"
  RESEND_API_KEY: "your-resend-key"
  RESEND_WEBHOOK_SECRET: "your-resend-webhook-secret"
